# Generated by Django 4.2.1 on 2023-06-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_background'),
    ]

    operations = [
        migrations.DeleteModel(
            name='background',
        ),
    ]
