# Generated by Django 4.2.1 on 2023-06-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_background'),
    ]

    operations = [
        migrations.DeleteModel(
            name='background',
        ),
    ]
